export const PERMISSIONS = {
  AUTH: {
    LOGIN: 'AUTH_LOGIN',
    REGISTER: 'AUTH_REGISTER',
    ME: 'AUTH_ME',
    RESET_PASSWORD: 'AUTH_RESET_PASSWORD',
    UPDATEME: 'AUTH_UPDATEME',
    CHANGE_PASSWORD: 'AUTH_CHANGE_PASSWORD',
  },
  FILE: {
    UPLOAD_PRESIGNED: 'FILE_UPLOAD_PRESIGNED',
    UPLOAD_CREATEOBJECT: 'FILE_UPLOAD_CREATEOBJECT',
  },
  NOTIF: {
    ALL: 'NOTIF_ALL',
    READ: 'NOTIF_READ',
    CREATE: 'NOTIF_CREATE',
    DELETE: 'NOTIF_DELETE',
  },
  TEST: {
    USE: 'TEST_USE',
  },
  TASK: {
    BOARD: {
      CREATE: 'TASK_BOARD_CREATE',
      UPDATE: 'TASK_BOARD_UPDATE',
      DELETE: 'TASK_BOARD_DELETE',
      ADD_MEMBERS: 'TASK_BOARD_ADD_MEMBERS',
      MODIFY_MEMBERS: 'TASK_BOARD_MODIFY_MEMBERS',
      DELETE_MEMBERS: 'TASK_BOARD_DELETE_MEMBERS',
      GET: 'TASK_BOARD_GET',
    },
    LIST: {
      CREATE: 'TASK_LIST_CREATE',
      UPDATE: 'TASK_LIST_UPDATE',
      DELETE: 'TASK_LIST_DELETE',
      GET: 'TASK_LIST_GET',
    },
    TASK: {
      CREATE: 'TASK_TASK_CREATE',
      UPDATE: 'TASK_TASK_UPDATE',
      DELETE: 'TASK_TASK_DELETE',
      ADD_FILE: 'TASK_TASK_ADD_FILE',
      DELETE_FILE: 'TASK_TASK_DELETE_FILE',
    },
  },
  EVENTS: {
    CALENDAR: {
      CREATE: 'EVENTS_CAL_CREATE',
      UPDATE: 'EVENTS_CAL_UPDATE',
      DELETE: 'EVENTS_CAL_DELETE',
      ADD_MEMBERS: 'EVENTS_CAL_ADD_MEMBERS',
      MODIFY_MEMBERS: 'EVENTS_CAL_MODIFY_MEMBERS',
      DELETE_MEMBERS: 'EVENTS_CAL_DELETE_MEMBERS',
      GET: 'EVENTS_CAL_GET',
    },
    EVENT: {
      CREATE: 'EVENTS_EVENT_CREATE',
      UPDATE: 'EVENTS_EVENT_UPDATE',
      DELETE: 'EVENTS_EVENT_DELETE',
      GET: 'EVENTS_EVENT_GET',
    },
  },
  DEPARTMENTS: {
    CREATE: 'DEPARTMENTS_CREATE',
    UPDATE: 'DEPARTMENTS_UPDATE',
    DELETE: 'DEPARTMENTS_DELETE',
    GET: 'DEPARTMENTS_GET',
  },
  POSITIONS: {
    CREATE: 'DEPARTMENTS_CREATE',
    UPDATE: 'DEPARTMENTS_UPDATE',
    DELETE: 'DEPARTMENTS_DELETE',
    GET: 'DEPARTMENTS_GET',
  },
  CONTACTS: {
    CREATE: 'CONTACTS_CREATE',
    UPDATE: 'CONTACTS_UPDATE',
    DELETE: 'CONTACTS_DELETE',
    GET: 'CONTACTS_GET',
  },
};
